version: '3.8'

services:
  # app:
  #   build:
  #     context: ./  # This is the path to your application code and Dockerfile
  #   depends_on:
  #     - pgdatabase
  pgdatabase:
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:8.2
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"


  
# docker compose up -d